services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../..:/workspace:cached
    network_mode: service:cosmos
  cosmos:
    container_name: cosmos
    restart: unless-stopped
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
