name: Build and Package

on:
  push:
    branches:
      - main
    paths:
      - src/**/*
      - public/**/*
      - .github/workflows/ci.yaml
      - next.config.ts
      - package.json
      - postcss.config.mjs
      - tailwind.config.ts
      - tsconfig.json
      - .eslintrc.json
  pull_request:
    branches:
      - main
    paths:
      - src/**/*
      - public/**/*
      - .github/workflows/ci.yaml
      - next.config.ts
      - package.json
      - postcss.config.mjs
      - tailwind.config.ts
      - tsconfig.json
      - .eslintrc.json

jobs:
  verify:
    if: github.ref != 'refs/heads/main'
    
    name: Verify source code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install
    
    - name: Lint code
      run: npm run lint
    
    - name: Run unit-tests
      run: npm run test

  package:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    name: Package docker container
    runs-on: ubuntu-latest
    needs: verify

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/promptyard:${{ github.sha }}